### ISSUE TITLE
Throws error when installed

### ISSUE THREAD

**Issue by at0g** [dpankros/meteor-autojoin#3]
Just installing this module throws the following error?

```
ReferenceError: __orig is not defined
W20150317-14:08:42.494(11)? (STDERR)     at Package (packages/dpankros:autojoin/meteor-autojoin.js:40:1)
```

I'm using the following versions:
- Meteor `1.0.3.2`
- aldeed:collection2 `2.3.2`
- aldeed:simple-schema `1.3.0`

**Comment by dpankros** [comment]
Looks like I committed the fix about two weeks ago but forgot to push it to the package repo.  Sorry about that. 

I discovered another issue that needs fixing before it will work, though.

**Comment by dpankros** [comment]
I pushed package so your issue should be resolved along with some other enhancements.  Reopen if it is not.  Thanks!
